### ISSUE TITLE
fails after updating, SyntaxError: Unexpected token '.' (line:75)

### ISSUE THREAD

**Issue by animalkingdoms** [cameo69/node-red-contrib-ratelimit#2]
@cameo69/node-red-ratelimit
0.0.18
SyntaxError: Unexpected token '.' (line:75)

nodes are disabled and 'unknown' after doing update
have tried uninstall -> restartnode-red -> install node-red-ratelimit

Issue persists

**Comment by cameo69** [comment]
Hi,
line 75 in v0.0.18 is `peek() { return head?.value },`.
From that I assume that you are using an old version of node that does not support optional chaining.
Seems unavailable in versions < v14.
<img width="1423" alt="image" src="https://github.com/cameo69/node-red-contrib-ratelimit/assets/44269764/debeaedc-f468-48e8-a83d-670efd797c34">
Can you confirm (check with `node -v`)?

**Comment by animalkingdoms** [comment]
version 12.22.12
Will have to look into update path.
Thank you

**Comment by cameo69** [comment]
Thank you for confirming this.

If you are keen to check (albeit I do not know if I have other parts that rely on newer node version), you can try to replace this one occurrence of optional chaining with something suitable for older versions as well.

To do so, find the file `ratelimit.js`, path probably something like `... node_modules/@cameo69/node-red-ratelimit/ratelimit.js` , find line 75 (it should be `peek() { return head?.value },`), and modify to `peek() { return head && head.value },`. Maybe this gives you a temporary solution until you can update node.

**Comment by animalkingdoms** [comment]
Thank you i have changed that and am not getting an error - it apears to rate limit correctly so far
